name: translit_uz
description: Simple dart package for converting Cyrillic Uzbek symbols to Translit UZ and back
version: 1.1.3

homepage: https://github.com/roman-romanov/translit_uz.git

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.9.4